name: Build APK
on: 
  push:
    branches: [main]
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    
    steps:
    - uses: actions/checkout@v2
    - uses: ugorji/buildozer-action@v1
    - uses: actions/upload-artifact@v2
      with:
        name: sklad-app
        path: bin/*.apk
